# 
#  Assassin configuration
#  for more information check
#  http://dev.bukkit.org/server-mods/assassin/
#  
General:
  debug_mode_enabled: false
  stats_tracking_enabled: true
  update_check_enabled: true
  config_version: 1.1.1
Assassin:
  active_length: 3600
  teleport_on_deactivate: true
  cooldown_length: 600
  messages_distance: 250
  warn_others_on_activation: true
  warn_others_when_near: true
  return_mask: false
  activation_cost: 0
  prevent_neutral_pvp: true
  particle_effects: true
  potion_effects: true
  warn_time_almost_up: 10
  blocked_commands:
  - /spawn
  - /home
  - /tp
  - /tphere
  - /tpa
  - /tpahere
  - /tpall
  - /tpaall