name: Assassin
author: TfT_02
main: com.me.tft_02.assassin.Assassin
description: A whole new concept on PVP!
dev-url: http://dev.bukkit.org/server-mods/Assassin/
version: 1.1.1
softdepend: [ThisPluginDoesNotExist]
commands:
   assassin:
      description: Usage /assassin help.
      permission: assassin.assassin
      permission-message: You don't have <permission>
permissions:
    assassin.*:
        description: Gives access to all commands
        default: op
        children:
            assassin.assassin: true
            assassin.info: true
            assassin.spawnmask: true
            assassin.commands.refresh: true
            assassin.commands.reload: true
    assassin.defaults:
        description: Gives access to default commands
        default: true
        children:
            assassin.assassin: true
            assassin.commands.*: true
    assassin.commands.*:
        description: Gives access to player commands
        children:
            assassin.commands.status: true
            assassin.commands.chat: true
            assassin.commands.deactivate: true
    assassin.assassin:
        description: Allows players to activate Assassin Mode.
        default: true
    assassin.info:
        description: Check your status and see how long you're in Assassin Mode.
        default: true
    assassin.spawnmask:
        description: Spawn Assassin masks.
        default: false
    assassin.refresh:
        description: Refresh the cooldown of a certain player.
        default: false
    assassin.deactivate:
        description: Deactivates Assasssin Mode of a certain player.
        default: false
    assassin.chat:
        description: Allows Assassins to chat with other Assassins.
        default: true
    assassin.admin:
        description: Permission node for admins, will send messages to players with this permission when Assassin is outdated.
        default: op