name: Assassin
version: ${project.version}-b${BUILD_NUMBER}
description: >
  A whole new concept on PVP! This plugin allows players to craft Assassin
  masks. When they equip these masks they will become anonymous and are able
  to attack and kill other players.

author: TfT_02
website: http://dev.bukkit.org/server-mods/Assassin/

main: com.me.tft_02.assassin.Assassin
softdepend: [ThisPluginDoesNotExist]

commands:
   assassin:
      description: Usage /assassin help.
      permission: assassin.commands.assassin
      permission-message: You don't have <permission>

permissions:
    assassin.*:
        description: Gives access to all commands
        default: op
        children:
            assassin.assassin: true
            assassin.info: true
            assassin.spawnmask: true
            assassin.commands.refresh: true
            assassin.commands.reload: true
    assassin.defaults:
        description: Gives access to default commands
        default: true
        children:
            assassin.assassin: true
            assassin.commands.all: true
    assassin.commands.all:
        description: Gives access to player commands
        children:
            assassin.commands.assassin: true
            assassin.commands.status: true
            assassin.commands.chat: true
            assassin.commands.deactivate: true
    assassin.assassin:
        description: Allows players to activate Assassin Mode.
        default: true
    assassin.info:
        description: Check your status and see how long you're in Assassin Mode.
        default: true
    assassin.spawnmask:
        description: Spawn Assassin masks.
        default: false
    assassin.refresh:
        description: Refresh the cooldown of a certain player.
        default: false
    assassin.deactivate:
        description: Deactivates Assasssin Mode of a certain player.
        default: false
    assassin.chat:
        description: Allows Assassins to chat with other Assassins.
        default: true
    assassin.admin:
        description: Permission node for admins, will send messages to players with this permission when Assassin is outdated.
        default: op